# Generated by Django 4.2.3 on 2023-07-23 14:43

import car_manager.common.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_name', models.CharField(choices=[('Insurance', 'Insurance'), ('Periodic tech inspections', 'Periodic tech inspections'), ('Toll taxes', 'Toll taxes')])),
                ('start_date', models.DateField(validators=[car_manager.common.validators.MinDateValidator(datetime.date(1900, 1, 1)), car_manager.common.validators.MaxDateValidator(datetime.date(2100, 1, 1))])),
                ('end_date', models.DateField(validators=[car_manager.common.validators.MinDateValidator(datetime.date(1900, 1, 1)), car_manager.common.validators.MaxDateValidator(datetime.date(2100, 1, 1))])),
                ('car_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carsmodel')),
            ],
        ),
    ]
