# Generated by Django 4.2.3 on 2023-07-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remindermodel',
            old_name='car_user',
            new_name='car',
        ),
    ]
