# Generated by Django 4.2.3 on 2023-07-23 14:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(choices=[('Opel', 'Opel'), ('Citroen', 'Citroen'), ('BMW', 'BMW')])),
                ('plate_number', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Enter Plate Number')),
                ('vin_number', models.CharField(max_length=17, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'My Cars',
            },
        ),
    ]
