# Generated by Django 4.2.3 on 2023-08-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carsmodel_options_alter_carsmodel_car_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='car_name',
            field=models.CharField(choices=[('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Ford', 'Ford'), ('Fiat', 'Fiat'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('VolksWagen', 'VolksWagen')]),
        ),
    ]
